apiVersion: v1
kind: Service
metadata:
  name: {{ include "docextract.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "docextract.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "docextract.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
